trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Build.Repository.LocalPath is:"
          Write-Host $(Build.Repository.LocalPath)
          Write-Host "Build.SourcesDirectory is:"
          Write-Host $(Build.SourcesDirectory)
          Write-Host "Agent.HomeDirectory	 is:"
          Write-Host $(Agent.HomeDirectory)

- stage: DBAVerificationScript
  displayName: 'Script database schema changes'
  jobs:
  - deployment: DBAVerificationScript
    pool:
      vmImage: 'windows-2019'
    variables:
    - group: 'Release'
    environment: 'dbaverificationscript'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2      
            displayName: Show Auto Generated SQL Script
            inputs:
              targetType: 'inline'
              script: | 
                Write-Host "Build.Repository.LocalPath is:"
                Write-Host $(Build.Repository.LocalPath)
                Write-Host "Build.SourcesDirectory is:"
                Write-Host $(Build.SourcesDirectory)
                Write-Host "Agent.ReleaseDirectory is:"
                Write-Host $(Agent.ReleaseDirectory)
                Write-Host "ENV:AGENT_RELEASEDIRECTORY is:"
                Write-Host $ENV:AGENT_RELEASEDIRECTORY